name: 同步源码

on:
  workflow_dispatch:
    inputs:
      update:
        description: '同步源码'
        default: '开始同步'

  schedule:
    - cron: 30 6,18 * * *

env: 
  TZ: Asia/Shanghai
  GITHUB_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
  WECHAT_WORK_URL: ${{ secrets.WECHAT_WORK_URL }}
  WECHAT_WORK_TOKEN: ${{ secrets.WECHAT_WORK_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

jobs:
  build:
    runs-on: Ubuntu-22.04

    name: Update ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [main,18.06,19.07,Lean-openwrt,Lienol-openwrt]  #[main,18.06,19.07,Lean-openwrt,Lienol-openwrt]  

    steps:
    - name: 准备完成
      uses: actions/checkout@v3

    - name: 初始化系统环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        echo "GIT_DATE=$(date "+%Y年%m月%d日-%H点%M分")" >> $GITHUB_ENV


    - name: 克隆源码
      env: 
        matrix_target: ${{matrix.target}}
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ${{matrix.target}}.sh
        git clone -b ${{matrix.target}} https://github.com/db-one/dbone-packages.git ${{matrix.target}}
        cd ${{matrix.target}}
        rm -Rf *
        git rm --cache *

        echo "执行脚本"
        $GITHUB_WORKSPACE/${{matrix.target}}.sh

        echo "复制文件..."
        [ -e $GITHUB_WORKSPACE/LICENSE ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/${{matrix.target}}

        if [ -n "$(ls -A "$GITHUB_WORKSPACE/files/${{matrix.target}}" 2>/dev/null)" ]; then
        cp -rf $GITHUB_WORKSPACE/files/${{matrix.target}}/* $GITHUB_WORKSPACE/${{matrix.target}}
        fi

    - name: 应用源码更新
      env: 
        GITHUB_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        git add .
        git commit -m "同步源码于$GIT_DATE" #|| true
        git push --quiet "https://${{ secrets.GIT_USER_TOKEN }}@github.com/db-one/dbone-packages.git" HEAD:${{matrix.target}}

    - name: 删除运行记录
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 3     #保留最后多少记录不删除
        keep_minimum_runs: 0



