name: 删除运行记录

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'delete'
        required: true
        default: '删除运行记录'

  schedule:
    - cron: 00 20 * * 1

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - name: 删除运行记录
        uses: db-one/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}       
          keep_minimum_runs: 5    #保留多少个记录不删除